### PR TITLE
GitHub actions

### PR DESCRIPTION
**Pull request by UziTech**
Use github actions for testing, linting and releasing with [semantic-release](https://github.com/semantic-release/semantic-release#-semantic-release)

You will need to add your APM [API Token](https://atom.io/account) to a GitHub [secret](https://github.com/sdinesh86/atom-music/settings/secrets) called `ATOM_ACCESS_TOKEN` for automatic releases.

### CODE REVIEW

**Comment by vivi90** [comment]
@UziTech @sdinesh86 Not able to use automatic releases because i have no settings acces to add the token.

**Comment by vivi90** [comment]
@UziTech Cherry-picked and released you spec test fix (https://github.com/sdinesh86/atom-music/commit/1395edc06361a310c313f5e0892fe94564f05245) until we have a solution for the settings problem.

**Comment by UziTech** [comment]
I can comment out the release if you want so we at least get the CI. Then when the settings issue is dealt with all you will have to do in uncomment the release for CD.

**Comment by vivi90** [comment]
@UziTech Yes, would be great. Please do so.

**Comment by UziTech** [comment]
I rebased and commented the release so this should be ready for testing and linting PRs

**Comment by vivi90** [comment]
@UziTech Great, thank you. Looks good, will merge it.

**Comment by vivi90** [comment]
@UziTech It seems you have missed something, because actions are not running.

**Comment by vivi90** [comment]
@UziTech Fixed by:
https://github.com/sdinesh86/atom-music/commit/4fdee02ad5f5dfea0b7967d60aa4175501f60f89 and https://github.com/sdinesh86/atom-music/commit/4052be173a65650869f43c58915545b3473a0f22

**Comment by UziTech** [comment]
oops acidentally created the .github folder inside the lib folder (❁´◡`❁)

**Comment by vivi90** [comment]
@UziTech No problem.

**Pull request merged**
